services:
  - type: web
    name: pintumex-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://hostname:3306/dbname
      - key: SPRING_DATASOURCE_USERNAME
        value: user
      - key: SPRING_DATASOURCE_PASSWORD
        value: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
