services:
  - type: web
    name: pintumex-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromSecret: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromSecret: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromSecret: SPRING_DATASOURCE_PASSWORD